# Standard augmentation configuration for vision models

# Basic augmentations
random_crop: true
crop_padding: 4

horizontal_flip: true
flip_prob: 0.5

vertical_flip: false
vertical_flip_prob: 0.0

rotation: true
rotation_degrees: 15

# Color augmentations
color_jitter: true
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.1

# Advanced augmentations
random_erasing: true
erasing_p: 0.25
erasing_scale: [0.02, 0.33]
erasing_ratio: [0.3, 3.3]

# Auto augmentation
auto_augment: false
auto_augment_policy: "imagenet"  # imagenet, cifar10, svhn

# RandAugment
rand_augment: false
rand_augment_n: 2
rand_augment_m: 9

# Mix augmentations (applied during training)
mixup: false
mixup_alpha: 0.2
mixup_prob: 0.5

cutmix: false
cutmix_alpha: 1.0
cutmix_prob: 0.5

# Normalization (dataset-specific, overridden by data configs)
normalize: true
mean: [0.485, 0.456, 0.406]  # ImageNet defaults
std: [0.229, 0.224, 0.225]

# Test-time augmentation
tta:
  enable: false
  n_augmentations: 5
  aggregation: "mean"  # mean, max, voting