# Default callback configuration

# Model Checkpointing
checkpoint:
  enable: true
  monitor: "val/loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  verbose: true
  filename: "{epoch:02d}-{val_loss:.4f}"
  auto_insert_metric_name: false

# Early Stopping
early_stopping:
  enable: false
  monitor: "val/loss"
  mode: "min"
  patience: 10
  min_delta: 0.001
  verbose: true

# Learning Rate Monitor
lr_monitor:
  enable: true
  logging_interval: "step"
  log_momentum: true

# Progress Bar
progress_bar:
  enable: true
  refresh_rate: 10
  leave: true

# Stochastic Weight Averaging
swa:
  enable: false
  swa_lrs: 0.05
  swa_epoch_start: 0.8
  annealing_epochs: 10
  annealing_strategy: "cos"

# Vision-specific callbacks
visualization:
  enable: false
  log_every_n_epochs: 5
  num_samples: 8

model_analysis:
  enable: false
  analyze_gradients: true
  analyze_weights: true
  analyze_activations: false

# Custom callbacks (names from registry)
custom: []